# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

In [3]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura em metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [4]:
lista_de_alturas = list(range(170, 190, 5))
print(lista_de_alturas)


# seu código aqui
altura_em_centimetros = np.array(lista_de_alturas)
print(altura_em_centimetros)

altura_em_metros = altura_em_centimetros / 100
print(altura_em_metros)

[170, 175, 180, 185]
[170 175 180 185]
[1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [5]:
lista_pesos = [70, 75, 80, 85]
# seu código aqui
pesos = np.array(lista_pesos)
print(pesos)

[70 75 80 85]


In [6]:
# calcule o IMC dessas pessoas
imc = pesos / (altura_em_metros ** 2)
print(imc)

[24.22145329 24.48979592 24.69135802 24.83564646]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [7]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
#i) transforme essa lista em um ndarray
nd_financeiros = np.array(dados_financeiros)
print('O array criado é:\n',nd_financeiros)

O array criado é:
 [[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [8]:
# ii) 
nd_financeiros = nd_financeiros.transpose()
print('O array transposto é:\n',nd_financeiros)

print('A segunda linha do array é:\n',nd_financeiros[1:2,:])
print('A segunda coluna do array é:\n',nd_financeiros[:,1:2])


O array transposto é:
 [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]
A segunda linha do array é:
 [[2500 2500 5500]]
A segunda coluna do array é:
 [[1000]
 [2500]
 [3000]
 [5000]]


In [9]:
# iii) Calcule o endividamento total
endividamento_total = []
for item in nd_financeiros:
    endividamento = (item[0] + item[1]) / item[2]
    print(endividamento)
    endividamento_total.append(endividamento)
print(endividamento_total)

0.6666666666666666
0.9090909090909091
0.5714285714285714
0.9375
[0.6666666666666666, 0.9090909090909091, 0.5714285714285714, 0.9375]


In [10]:
#calculando o endividamento total usando a função lambda e o map
#apenas para exercitar programação funcional
endividamento_total = map((lambda item: (item[0] + item[1]) / item[2]), nd_financeiros)
print(list(endividamento_total))

[0.6666666666666666, 0.9090909090909091, 0.5714285714285714, 0.9375]


In [11]:
# iv) corrigindo um valor específico
nd_financeiros[2][2] = 10000
print(nd_financeiros)
endividamento_total = map((lambda item: (item[0] + item[1]) / item[2]), nd_financeiros)
print(list(endividamento_total))

[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000 10000]
 [10000  5000 16000]]
[0.6666666666666666, 0.9090909090909091, 0.4, 0.9375]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [12]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3,100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [13]:
# i) crie o objeto bool_zero através do operador ==
bool_zero = poi == 0
bool_zero

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [14]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)
#somando os elementos de bool_zero
qtd = np.sum(bool_zero, where='0')
#contando a quantidade de zeros
qtd1 = poi[poi==0].shape[0]
#imprimindo as duas contagens
print(qtd)
print(qtd1)


6
6


In [21]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero
#experimentando a inversão com operador ~
bool_zero_invertido = ~bool_zero
#experimentando a inversão com método np.invert()
bool_zero_invertido_2 = np.invert(bool_zero)

print(bool_zero)
print(bool_zero_invertido)
print(bool_zero_invertido_2)

#selecionando os valores iguais a zero
print(poi[bool_zero])

#selecionando os valores diferentes de zero
print(poi[bool_zero_invertido])

[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]
[ True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True  True  True False  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True 

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=690ec1aa-ed7a-4520-b902-aba6fc5867d1' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>